import Head from "next/head";
import Header from "../components/Header";
import CollectionCard from "../components/CollectionCard";
import Main from "../components/Main";
import { useState } from "react";

export default function Home({ result }) {
  const [selectedPunk, setSelectedPunk] = useState(0);

  return (
    <div className="gradient-bg text-white h-full min-h-screen max-w-screen">
      <Head>
        <title>ZH thirdweb NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {result.assets?.length > 0 ? (
        <>
          <Main selectedPunk={selectedPunk} result={result} />
          <main className="flex items-center justify-center">
            <div className="mx-auto grid grid-flow-row-dense md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 p-5 gap-5">
              {result?.assets?.map((nftData) => (
                <CollectionCard
                  key={nftData.token_id}
                  id={nftData.token_id}
                  name={nftData.name}
                  traits={nftData.traits}
                  image={nftData.image_original_url}
                  setSelectedPunk={setSelectedPunk}
                />
              ))}
            </div>
          </main>
        </>
      ) : (
        <>
          <h1 className="text-center text-xl">Loading....</h1>
        </>
      )}
    </div>
  );
}

export async function getServerSideProps() {
  // Call an external API endpoint to get posts
  const address = process.env.NEXT_ETH_ADDRES;
  const address2 = null;

  const url = `https://testnets-api.opensea.io/assets?asset_contract_address=${address}&order_direction=asc`;
  const res = await fetch(url);
  const result = await res.json();

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      result,
    },
  };
}
